#!/usr/bin/env bash

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/nelong.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/nelong.com

  # set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:6054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/ordererOrg/ca-cert.pem"
  # { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/nelong.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/nelong.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/nelong.com/msp/tlscacerts/tlsca.nelong.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/nelong.com/tlsca"
  cp "${PWD}/organizations/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/nelong.com/tlsca/tlsca.nelong.com-cert.pem"

# Loop through each orderer (orderer, orderer2, orderer3, orderer4) to register and generate artifacts
  for ORDERER in orderer orderer2 orderer3 orderer4; do
    infoln "Registering ${ORDERER}"
    # set -x
    fabric-ca-client register --caname ca-orderer --id.name ${ORDERER} --id.secret ${ORDERER}pw --id.type orderer --tls.certfiles "${PWD}/organizations/ordererOrg/ca-cert.pem"
    # { set +x; } 2>/dev/null

    infoln "Generating the ${ORDERER} MSP"
    # set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:6054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/msp" --tls.certfiles "${PWD}/organizations/ordererOrg/ca-cert.pem"
    # { set +x; } 2>/dev/null

    cp "${PWD}/organizations/ordererOrganizations/nelong.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/msp/config.yaml"

    # Workaround: Rename the signcert file to ensure consistency with Cryptogen generated artifacts
    mv "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/msp/signcerts/cert.pem" "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/msp/signcerts/${ORDERER}.nelong.com-cert.pem"

    infoln "Generating the ${ORDERER} TLS certificates, use --csr.hosts to specify Subject Alternative Names"
    # set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:6054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/tls" --enrollment.profile tls --csr.hosts ${ORDERER}.nelong.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/ordererOrg/ca-cert.pem"
    # { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
    cp "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/tls/ca.crt"
    cp "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/tls/server.crt"
    cp "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/tls/server.key"

    # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
    mkdir -p "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/msp/tlscacerts"
    cp "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/nelong.com/orderers/${ORDERER}.nelong.com/msp/tlscacerts/tlsca.nelong.com-cert.pem"
  done

  # Register and generate artifacts for the orderer admin
  infoln "Registering the orderer admin"
  # set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/ordererOrg/ca-cert.pem"
  # { set +x; } 2>/dev/null

  infoln "Generating the admin msp"
  # set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:6054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/nelong.com/users/Admin@nelong.com/msp" --tls.certfiles "${PWD}/organizations/ordererOrg/ca-cert.pem"
  # { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/nelong.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/nelong.com/users/Admin@nelong.com/msp/config.yaml"
}


function createOrg() {
  local ORG_NUM=$1        # 1 (對應到org1)
  local ORG=$2            # Org1
  local PORT=$((7054 + (ORG_NUM - 1) * 1000))

  local DOMAIN="org${ORG_NUM}.nelong.com"
  local CA_NAME="ca-org${ORG_NUM}"
  local ORG_PATH="${PWD}/organizations/peerOrganizations/${DOMAIN}"

  infoln "Enrolling the CA admin for ${ORG}"
  mkdir -p "${ORG_PATH}"

  export FABRIC_CA_CLIENT_HOME=${ORG_PATH}
  # set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:${PORT} --caname ${CA_NAME} --tls.certfiles "${PWD}/organizations/org${ORG_NUM}/ca-cert.pem"
  # { set +x; } 2>/dev/null

  echo "NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-${PORT}-${CA_NAME}.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-${PORT}-${CA_NAME}.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-${PORT}-${CA_NAME}.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-${PORT}-${CA_NAME}.pem
    OrganizationalUnitIdentifier: orderer" > "${ORG_PATH}/msp/config.yaml"

  mkdir -p "${ORG_PATH}/msp/tlscacerts"
  cp "${PWD}/organizations/org${ORG_NUM}/ca-cert.pem" "${ORG_PATH}/msp/tlscacerts/ca.crt"

  mkdir -p "${ORG_PATH}/tlsca"
  cp "${PWD}/organizations/org${ORG_NUM}/ca-cert.pem" "${ORG_PATH}/tlsca/tlsca.${DOMAIN}-cert.pem"

  mkdir -p "${ORG_PATH}/ca"
  cp "${PWD}/organizations/org${ORG_NUM}/ca-cert.pem" "${ORG_PATH}/ca/ca.${DOMAIN}-cert.pem"

  infoln "Registering peer0"
  # set -x
  fabric-ca-client register --caname ${CA_NAME} --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/org${ORG_NUM}/ca-cert.pem"
  # { set +x; } 2>/dev/null

  infoln "Registering user"
  # set -x
  fabric-ca-client register --caname ${CA_NAME} --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/org${ORG_NUM}/ca-cert.pem"
  # { set +x; } 2>/dev/null

  infoln "Registering the ${ORG} admin"
  # set -x
  fabric-ca-client register --caname ${CA_NAME} --id.name ${ORG,,}admin --id.secret ${ORG,,}adminpw --id.type admin --tls.certfiles "${PWD}/organizations/org${ORG_NUM}/ca-cert.pem"
  # { set +x; } 2>/dev/null

  infoln "Generating the peer0 MSP"
  # set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:${PORT} --caname ${CA_NAME} -M "${ORG_PATH}/peers/peer0.${DOMAIN}/msp" --tls.certfiles "${PWD}/organizations/org${ORG_NUM}/ca-cert.pem"
  # { set +x; } 2>/dev/null

  cp "${ORG_PATH}/msp/config.yaml" "${ORG_PATH}/peers/peer0.${DOMAIN}/msp/config.yaml"

  infoln "Generating the peer0 TLS certs"
  # set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:${PORT} --caname ${CA_NAME} -M "${ORG_PATH}/peers/peer0.${DOMAIN}/tls" --enrollment.profile tls --csr.hosts peer0.${DOMAIN} --csr.hosts localhost --tls.certfiles "${PWD}/organizations/org${ORG_NUM}/ca-cert.pem"
  # { set +x; } 2>/dev/null

  cp "${ORG_PATH}/peers/peer0.${DOMAIN}/tls/tlscacerts/"* "${ORG_PATH}/peers/peer0.${DOMAIN}/tls/ca.crt"
  cp "${ORG_PATH}/peers/peer0.${DOMAIN}/tls/signcerts/"* "${ORG_PATH}/peers/peer0.${DOMAIN}/tls/server.crt"
  cp "${ORG_PATH}/peers/peer0.${DOMAIN}/tls/keystore/"* "${ORG_PATH}/peers/peer0.${DOMAIN}/tls/server.key"

  infoln "Generating the user MSP"
  # set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:${PORT} --caname ${CA_NAME} -M "${ORG_PATH}/users/User1@${DOMAIN}/msp" --tls.certfiles "${PWD}/organizations/org${ORG_NUM}/ca-cert.pem"
  # { set +x; } 2>/dev/null

  cp "${ORG_PATH}/msp/config.yaml" "${ORG_PATH}/users/User1@${DOMAIN}/msp/config.yaml"

  infoln "Generating the ${ORG} admin MSP"
  # set -x
  fabric-ca-client enroll -u https://${ORG,,}admin:${ORG,,}adminpw@localhost:${PORT} --caname ${CA_NAME} -M "${ORG_PATH}/users/Admin@${DOMAIN}/msp" --tls.certfiles "${PWD}/organizations/org${ORG_NUM}/ca-cert.pem"
  # { set +x; } 2>/dev/null

  cp "${ORG_PATH}/msp/config.yaml" "${ORG_PATH}/users/Admin@${DOMAIN}/msp/config.yaml"
}
