version: '3.7'
services:

  peer0.org1.nelong.com:
      container_name: peer0.org1.nelong.com
      image: hyperledger/fabric-peer:latest
      labels:
        service: hyperledger-fabric
      environment:
        #Generic peer variables
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_nelong
      volumes:
        - ./docker/peercfg:/etc/hyperledger/peercfg
        - /var/run/docker.sock:/host/var/run/docker.sock
        
  
  peer0.org2.nelong.com:
      container_name: peer0.org2.nelong.com
      image: hyperledger/fabric-peer:latest
      labels:
        service: hyperledger-fabric
      environment:
        #Generic peer variables
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_nelong
      volumes:
        - ./docker/peercfg:/etc/hyperledger/peercfg
        - /var/run/docker.sock:/host/var/run/docker.sock
        
  
